spring:
  application:
    name: SwiftTravel

  datasource:
    url: jdbc:mysql://localhost:3306/swift_travel?useSSL=false&serverTimezone=UTC
    username: ${SWIFT_TRAVEL_DB_USERNAME} # 这部分由于涉及到个人隐私，需要根据各自电脑进行修改
    password: ${SWIFT_TRAVEL_DB_PASSWORD} # 这部分由于涉及到个人隐私，需要根据各自电脑进行修改
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: localhost
      port: 6379
      password: ""


server:
  port: 8080
  # ssl: 
  #   enabled: true
  #   key-store: classpath:keystore.p12
  #   key-store-password: SwiftTravel
  #   key-store-type: PKCS12
  #   key-alias: SSLKEY


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

  global-config:
    enable-sql-runner: true
    db-config:
      id-type: input
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: swift_travel_

  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.setravel.swifttravel.entities